In [44]:
import pandas as pd
bitdata = pd.read_csv('preprocessed1.csv')
print(bitdata)

       Unnamed: 0         id        price    amount   sell        date  \
0               0  183601815  7349.600000  0.004568  False  2018-02-02
1               1  183601825  7354.680450  0.010000   True  2018-02-02
2               2  183601823  7354.680450  0.004568   True  2018-02-02
3               3  183601833  7354.600000  0.102395  False  2018-02-02
4               4  183601904  7343.407500  0.086580  False  2018-02-02
5               5  183601906  7343.807250  0.204920  False  2018-02-02
6               6  183602055  7356.000000  0.300000  False  2018-02-02
7               7  183602057  7357.900000  0.088007  False  2018-02-02
8               8  183602052  7355.800000  0.100000  False  2018-02-02
9               9  183602064  7343.167650  0.088007  False  2018-02-02
10             10  183602333  7352.281950  0.002000   True  2018-02-02
11             11  183602610  7351.320200  0.300000   True  2018-02-02
12             12  183602612  7351.320200  0.300000   True  2018-02-02
13             13  183602618  7348.321701  0.300000   True  2018-02-02
14             14  183602629  7339.326204  0.300000   True  2018-02-02
15             15  183602624  7344.323702  0.300000   True  2018-02-02
16             16  183602627  7339.825954  0.100000   True  2018-02-02
17             17  183602676  7338.854490  0.004885   True  2018-02-02
18             18  183602733  7338.934400  0.070000  False  2018-02-02
19             19  183602739  7340.372780  0.202579  False  2018-02-02
20             20  183602735  7339.653590  0.400000  False  2018-02-02
21             21  183602731  7338.934400  0.021287  False  2018-02-02
22             22  183602737  7339.653590  0.600000  False  2018-02-02
23             23  183602772  7361.900000  0.599912  False  2018-02-02
24             24  183602835  7339.900000  0.171953   True  2018-02-02
25             25  183602844  7339.900000  0.420000   True  2018-02-02
26             26  183602895  7339.893320  0.241449  False  2018-02-02
27             27  183603483  7334.700000  1.000000   True  2018-02-02
28             28  183604043  7311.765000  0.591953   True  2018-02-02
29             29  183604261  7300.000000  0.010000   True  2018-02-02
...           ...        ...          ...       ...    ...         ...
15685       15685  185088490  7151.289936  0.020000   True  2018-02-03
15686       15686  185088492  7151.209666  0.392500   True  2018-02-03
15687       15687  185088494  7151.209666  0.600000   True  2018-02-03
15688       15688  185088507  7151.000000  0.784800  False  2018-02-03
15689       15689  185088721  7153.457237  0.002970   True  2018-02-03
15690       15690  185089418  7148.000000  0.321677  False  2018-02-03
15691       15691  185089519  7140.373162  0.004848  False  2018-02-03
15692       15692  185089521  7140.373162  0.004708  False  2018-02-03
15693       15693  185089525  7140.373162  0.106910  False  2018-02-03
15694       15694  185089517  7140.373162  0.087147  False  2018-02-03
15695       15695  185089523  7140.373162  0.046387  False  2018-02-03
15696       15696  185089729  7131.100000  0.144122  False  2018-02-03
15697       15697  185089740  7131.100000  0.010000  False  2018-02-03
15698       15698  185089799  7124.000000  1.500000   True  2018-02-03
15699       15699  185089846  7123.275566  0.154769  False  2018-02-03
15700       15700  185090070  7140.500000  0.100000  False  2018-02-03
15701       15701  185090067  7140.300000  0.099993  False  2018-02-03
15702       15702  185090085  7141.000000  0.100000  False  2018-02-03
15703       15703  185090106  7145.200000  0.077792  False  2018-02-03
15704       15704  185090112  7151.100000  0.006111  False  2018-02-03
15705       15705  185090110  7150.900000  0.100000  False  2018-02-03
15706       15706  185090357  7142.000000  1.687097   True  2018-02-03
15707       15707  185090361  7142.000000  0.939920   True  2018-02-03
15708       15708  185090429  7126.100000  0.106258   True  2018-02-03
15709       15709  185090427  7130.400000  0.100000   True  2018-02-03
15710       15710  185090480  7123.500000  0.100000   True  2018-02-03
15711       15711  185090657  7128.172061  0.030500   True  2018-02-03
15712       15712  185090708  7134.433152  0.024440  False  2018-02-03
15713       15713  185090729  7136.199101  0.010000   True  2018-02-03
15714       15714  185090748  7136.200000  0.006030   True  2018-02-03

           time  hours  minutes  seconds hour_minute
0      02:00:08      2        0        8       02:00
1      02:00:09      2        0        9       02:00
2      02:00:09      2        0        9       02:00
3      02:00:10      2        0       10       02:00
4      02:00:26      2        0       26       02:00
5      02:00:26      2        0       26       02:00
6      02:00:38      2        0       38       02:00
7      02:00:38      2        0       38       02:00
8      02:00:38      2        0       38       02:00
9      02:00:39      2        0       39       02:00
10     02:01:15      2        1       15       02:01
11     02:01:55      2        1       55       02:01
12     02:01:55      2        1       55       02:01
13     02:01:55      2        1       55       02:01
14     02:01:55      2        1       55       02:01
15     02:01:55      2        1       55       02:01
16     02:01:55      2        1       55       02:01
17     02:02:00      2        2        0       02:02
18     02:02:07      2        2        7       02:02
19     02:02:07      2        2        7       02:02
20     02:02:07      2        2        7       02:02
21     02:02:07      2        2        7       02:02
22     02:02:07      2        2        7       02:02
23     02:02:11      2        2       11       02:02
24     02:02:19      2        2       19       02:02
25     02:02:21      2        2       21       02:02
26     02:02:36      2        2       36       02:02
27     02:04:31      2        4       31       02:04
28     02:05:02      2        5        2       02:05
29     02:05:15      2        5       15       02:05
...         ...    ...      ...      ...         ...
15685  01:54:35      1       54       35       01:54
15686  01:54:35      1       54       35       01:54
15687  01:54:35      1       54       35       01:54
15688  01:54:36      1       54       36       01:54
15689  01:55:06      1       55        6       01:55
15690  01:56:04      1       56        4       01:56
15691  01:56:23      1       56       23       01:56
15692  01:56:23      1       56       23       01:56
15693  01:56:23      1       56       23       01:56
15694  01:56:23      1       56       23       01:56
15695  01:56:23      1       56       23       01:56
15696  01:56:53      1       56       53       01:56
15697  01:56:54      1       56       54       01:56
15698  01:57:00      1       57        0       01:57
15699  01:57:09      1       57        9       01:57
15700  01:58:05      1       58        5       01:58
15701  01:58:05      1       58        5       01:58
15702  01:58:07      1       58        7       01:58
15703  01:58:10      1       58       10       01:58
15704  01:58:11      1       58       11       01:58
15705  01:58:11      1       58       11       01:58
15706  01:58:44      1       58       44       01:58
15707  01:58:45      1       58       45       01:58
15708  01:58:53      1       58       53       01:58
15709  01:58:53      1       58       53       01:58
15710  01:58:58      1       58       58       01:58
15711  01:59:17      1       59       17       01:59
15712  01:59:22      1       59       22       01:59
15713  01:59:33      1       59       33       01:59
15714  01:59:33      1       59       33       01:59

[15715 rows x 11 columns]

In [45]:
import numpy as np

result = np.array([])

price = bitdata['price']

for i in range(len(price)-9):
    result = np.append(result,np.sum(price[i:i+10])/10)
    
    
result = pd.DataFrame(result.reshape(-1,1))
result.columns = ['SMA']
print(result)

               SMA
0      7351.364330
1      7351.632525
2      7351.296500
3      7350.960475
4      7350.332645
5      7349.924516
6      7349.976161
7      7348.358756
8      7346.454205
9      7344.767645
10     7344.488158
11     7343.225322
12     7341.986742
13     7340.820081
14     7342.177911
15     7342.235291
16     7341.792920
17     7341.799657
18     7341.384208
19     7338.667268
20     7334.629990
21     7330.434631
22     7326.199401
23     7321.444042
24     7312.435042
25     7305.626042
26     7296.826042
27     7288.026710
28     7279.706710
29     7273.670210
...            ...
15676  7124.188564
15677  7130.309531
15678  7136.490352
15679  7143.822154
15680  7146.067878
15681  7147.737617
15682  7147.874933
15683  7148.012249
15684  7147.849565
15685  7146.765915
15686  7145.674238
15687  7143.663271
15688  7141.652304
15689  7138.952304
15690  7135.934137
15691  7135.184137
15692  7135.176821
15693  7135.239505
15694  7135.722189
15695  7136.794873
15696  7137.847557
15697  7138.937557
15698  7140.027557
15699  7140.237557
15700  7140.950000
15701  7139.250000
15702  7138.037206
15703  7137.380521
15704  7136.480431
15705  7134.990431

[15706 rows x 1 columns]

In [47]:
result2 = np.array([])

price = bitdata['price']

coe = np.array([1,2,3,4,5,6,7,8,9,10])
#print(coe*price[0:10])

for i in range(len(price)-9):
    result2 = np.append(result2,np.sum(price[i:i+10]*coe)/55)
    
    
result2 = pd.DataFrame(result2.reshape(-1,1))
result2.columns = ['EWM']
print(result2)

               EWM
0      7351.097450
1      7351.264290
2      7351.207504
3      7351.211813
4      7350.732036
5      7348.730865
6      7347.712535
7      7345.867043
8      7344.138994
9      7342.771757
10     7341.972691
11     7341.093678
12     7340.313511
13     7339.889301
14     7343.722014
15     7343.307848
16     7342.883250
17     7342.537868
18     7341.247021
19     7335.861711
20     7328.831298
21     7322.116755
22     7315.961749
23     7309.761858
24     7300.737487
25     7293.351115
26     7283.582744
27     7275.414373
28     7268.773153
29     7263.626478
...            ...
15676  7136.348150
15677  7141.261077
15678  7145.061102
15679  7147.699220
15680  7149.451053
15681  7149.802348
15682  7148.463356
15683  7147.099397
15684  7145.710472
15685  7144.351126
15686  7143.188807
15687  7140.538946
15688  7138.254715
15689  7135.045205
15690  7132.194889
15691  7133.025046
15692  7133.955203
15693  7135.013962
15694  7136.824962
15695  7139.620927
15696  7142.185496
15697  7142.940485
15698  7143.497293
15699  7140.965010
15700  7139.176364
15701  7136.003636
15702  7133.989466
15703  7133.334183
15704  7133.119379
15705  7133.068392

[15706 rows x 1 columns]

In [50]:
result = result.join(result2)

In [51]:
result.to_csv('SMA&EWM.csv',index=False)