In [1]:
import pandas as pd

import dateandtime

import new_process

In [2]:
bitdata = pd.read_csv('tIOSBTC.csv')

new_process.preprocess(bitdata)

bitdata = pd.read_csv('tIOSBTC.csv')

,ID,MTS,AMOUNT,PRICE,time,hours,minutes,seconds,hour_minute
0,264428531,2018-07-02,-0.200000,6622.000000,18:53:00.219000,18,53,00.219000,18:53
1,264428520,2018-07-02,-0.290001,6622.000000,18:52:54.735000,18,52,54.735000,18:52
2,264428512,2018-07-02,0.118359,6622.100000,18:52:50.966000,18,52,50.966000,18:52
3,264428511,2018-07-02,0.432000,6622.100000,18:52:50.963000,18,52,50.963000,18:52
4,264428510,2018-07-02,0.302020,6622.100000,18:52:50.961000,18,52,50.961000,18:52
5,264428509,2018-07-02,0.147621,6622.100000,18:52:50.957000,18,52,50.957000,18:52
6,264428506,2018-07-02,0.002379,6622.100000,18:52:49.359000,18,52,49.359000,18:52
7,264428505,2018-07-02,0.010000,6622.100000,18:52:49.357000,18,52,49.357000,18:52
8,264428495,2018-07-02,-0.133438,6622.000000,18:52:46.557000,18,52,46.557000,18:52
9,264428494,2018-07-02,-0.086557,6622.000000,18:52:46.555000,18,52,46.555000,18:52
10,264428482,2018-07-02,-0.251479,6622.000000,18:52:43.983000,18,52,43.983000,18:52
11,264428453,2018-07-02,-0.121000,6622.000000,18:52:36.254000,18,52,36.254000,18:52
12,264428437,2018-07-02,-0.020000,6622.000000,18:52:30.205000,18,52,30.205000,18:52
13,264428424,2018-07-02,0.063056,6622.300000,18:52:28.494000,18,52,28.494000,18:52
14,264428416,2018-07-02,-0.015000,6622.000000,18:52:24.975000,18,52,24.975000,18:52
15,264428415,2018-07-02,-0.030000,6622.100000,18:52:24.973000,18,52,24.973000,18:52
16,264428408,2018-07-02,-0.970000,6622.000000,18:52:22.010000,18,52,22.010000,18:52
17,264428407,2018-07-02,-0.030000,6622.200000,18:52:22.007000,18,52,22.007000,18:52
18,264428398,2018-07-02,-0.010000,6622.000000,18:52:18.848000,18,52,18.848000,18:52
19,264428397,2018-07-02,-0.290000,6622.000000,18:52:18.580000,18,52,18.580000,18:52
20,264428392,2018-07-02,0.068251,6622.100000,18:52:17.596000,18,52,17.596000,18:52
21,264428391,2018-07-02,0.030000,6622.100000,18:52:17.594000,18,52,17.594000,18:52
22,264428390,2018-07-02,0.090000,6622.100000,18:52:17.591000,18,52,17.591000,18:52
23,264428389,2018-07-02,-0.100000,6622.000000,18:52:17.551000,18,52,17.551000,18:52
24,264428384,2018-07-02,-0.100000,6622.000000,18:52:15.044000,18,52,15.044000,18:52
25,264428370,2018-07-02,-0.100000,6622.000000,18:52:10.716000,18,52,10.716000,18:52
26,264428363,2018-07-02,-1.930000,6622.000000,18:52:07.398000,18,52,07.398000,18:52
27,264428362,2018-07-02,0.010000,6622.100000,18:52:07.358000,18,52,07.358000,18:52
28,264428346,2018-07-02,0.187915,6622.100000,18:52:05.556000,18,52,05.556000,18:52
29,264428345,2018-07-02,0.111035,6622.100000,18:52:05.553000,18,52,05.553000,18:52
...,...,...,...,...,...,...,...,...,...
995,264421246,2018-07-02,-0.010000,6607.000000,18:29:00.680000,18,29,00.680000,18:29
996,264421245,2018-07-02,-0.010000,6607.000000,18:29:00.674000,18,29,00.674000,18:29
997,264421244,2018-07-02,-0.010000,6607.000000,18:29:00.669000,18,29,00.669000,18:29
998,264421243,2018-07-02,-0.005000,6607.000000,18:29:00.663000,18,29,00.663000,18:29
999,264421242,2018-07-02,-0.010000,6607.000000,18:29:00.657000,18,29,00.657000,18:29
1000,264428531,2018-07-02,-0.200000,6622.000000,18:53:00.219000,18,53,00.219000,18:53
1001,264428531,2018-07-02,-0.200000,6622.000000,18:53:00.219000,18,53,00.219000,18:53
1002,264428531,2018-07-02,-0.200000,6622.000000,18:53:00.219000,18,53,00.219000,18:53
1003,264428539,2018-07-02,0.005000,6622.100000,18:53:04.551000,18,53,04.551000,18:53
1004,264428531,2018-07-02,-0.200000,6622.000000,18:53:00.219000,18,53,00.219000,18:53
1005,264428547,2018-07-02,-0.329468,6620.900000,18:53:05.065000,18,53,05.065000,18:53
1006,264428546,2018-07-02,-0.030000,6621.900000,18:53:05.064000,18,53,05.064000,18:53
1007,264428545,2018-07-02,-0.850000,6622.000000,18:53:05.061000,18,53,05.061000,18:53
1008,264428544,2018-07-02,-1.787586,6622.000000,18:53:05.059000,18,53,05.059000,18:53
1009,264428539,2018-07-02,0.005000,6622.100000,18:53:04.551000,18,53,04.551000,18:53
1010,264428547,2018-07-02,-0.329468,6620.900000,18:53:05.065000,18,53,05.065000,18:53
1011,264428547,2018-07-02,-0.329468,6620.900000,18:53:05.065000,18,53,05.065000,18:53
1012,264428569,2018-07-02,-1.000000,6618.000000,18:53:08.538000,18,53,08.538000,18:53
1013,264428568,2018-07-02,-0.517577,6618.000000,18:53:08.116000,18,53,08.116000,18:53
1014,264428567,2018-07-02,-0.158900,6618.000000,18:53:08.114000,18,53,08.114000,18:53
1015,264428566,2018-07-02,-0.004000,6618.000000,18:53:08.113000,18,53,08.113000,18:53
1016,264428565,2018-07-02,-0.868523,6618.663936,18:53:08.111000,18,53,08.111000,18:53
1017,264428563,2018-07-02,-0.641477,6618.663936,18:53:08.106000,18,53,08.106000,18:53
1018,264428561,2018-07-02,-0.174623,6619.100000,18:53:08.101000,18,53,08.101000,18:53
1019,264428560,2018-07-02,-0.050000,6619.200000,18:53:08.099000,18,53,08.099000,18:53
1020,264428559,2018-07-02,-0.081900,6619.600000,18:53:08.096000,18,53,08.096000,18:53
1021,264428558,2018-07-02,-0.030000,6619.900000,18:53:08.094000,18,53,08.094000,18:53
1022,264428557,2018-07-02,-0.002000,6620.000000,18:53:08.091000,18,53,08.091000,18:53
1023,264428547,2018-07-02,-0.329468,6620.900000,18:53:05.065000,18,53,05.065000,18:53
1024,264428569,2018-07-02,-1.000000,6618.000000,18:53:08.538000,18,53,08.538000,18:53