In [3]:
import pandas as pd

data = pd.read_csv('data_edited.csv')

       Unnamed: 0         id        price    amount   sell        date  \
0               0  183601815  7349.600000  0.004568  False  2018-02-02
1               1  183601825  7354.680450  0.010000   True  2018-02-02
2               2  183601823  7354.680450  0.004568   True  2018-02-02
3               3  183601833  7354.600000  0.102395  False  2018-02-02
4               4  183601904  7343.407500  0.086580  False  2018-02-02
5               5  183601906  7343.807250  0.204920  False  2018-02-02
6               6  183602055  7356.000000  0.300000  False  2018-02-02
7               7  183602057  7357.900000  0.088007  False  2018-02-02
8               8  183602052  7355.800000  0.100000  False  2018-02-02
9               9  183602064  7343.167650  0.088007  False  2018-02-02
10             10  183602333  7352.281950  0.002000   True  2018-02-02
11             11  183602610  7351.320200  0.300000   True  2018-02-02
12             12  183602612  7351.320200  0.300000   True  2018-02-02
13             13  183602618  7348.321701  0.300000   True  2018-02-02
14             14  183602629  7339.326204  0.300000   True  2018-02-02
15             15  183602624  7344.323702  0.300000   True  2018-02-02
16             16  183602627  7339.825954  0.100000   True  2018-02-02
17             17  183602676  7338.854490  0.004885   True  2018-02-02
18             18  183602733  7338.934400  0.070000  False  2018-02-02
19             19  183602739  7340.372780  0.202579  False  2018-02-02
20             20  183602735  7339.653590  0.400000  False  2018-02-02
21             21  183602731  7338.934400  0.021287  False  2018-02-02
22             22  183602737  7339.653590  0.600000  False  2018-02-02
23             23  183602772  7361.900000  0.599912  False  2018-02-02
24             24  183602835  7339.900000  0.171953   True  2018-02-02
25             25  183602844  7339.900000  0.420000   True  2018-02-02
26             26  183602895  7339.893320  0.241449  False  2018-02-02
27             27  183603483  7334.700000  1.000000   True  2018-02-02
28             28  183604043  7311.765000  0.591953   True  2018-02-02
29             29  183604261  7300.000000  0.010000   True  2018-02-02
...           ...        ...          ...       ...    ...         ...
15685       15685  185088490  7151.289936  0.020000   True  2018-02-03
15686       15686  185088492  7151.209666  0.392500   True  2018-02-03
15687       15687  185088494  7151.209666  0.600000   True  2018-02-03
15688       15688  185088507  7151.000000  0.784800  False  2018-02-03
15689       15689  185088721  7153.457237  0.002970   True  2018-02-03
15690       15690  185089418  7148.000000  0.321677  False  2018-02-03
15691       15691  185089519  7140.373162  0.004848  False  2018-02-03
15692       15692  185089521  7140.373162  0.004708  False  2018-02-03
15693       15693  185089525  7140.373162  0.106910  False  2018-02-03
15694       15694  185089517  7140.373162  0.087147  False  2018-02-03
15695       15695  185089523  7140.373162  0.046387  False  2018-02-03
15696       15696  185089729  7131.100000  0.144122  False  2018-02-03
15697       15697  185089740  7131.100000  0.010000  False  2018-02-03
15698       15698  185089799  7124.000000  1.500000   True  2018-02-03
15699       15699  185089846  7123.275566  0.154769  False  2018-02-03
15700       15700  185090070  7140.500000  0.100000  False  2018-02-03
15701       15701  185090067  7140.300000  0.099993  False  2018-02-03
15702       15702  185090085  7141.000000  0.100000  False  2018-02-03
15703       15703  185090106  7145.200000  0.077792  False  2018-02-03
15704       15704  185090112  7151.100000  0.006111  False  2018-02-03
15705       15705  185090110  7150.900000  0.100000  False  2018-02-03
15706       15706  185090357  7142.000000  1.687097   True  2018-02-03
15707       15707  185090361  7142.000000  0.939920   True  2018-02-03
15708       15708  185090429  7126.100000  0.106258   True  2018-02-03
15709       15709  185090427  7130.400000  0.100000   True  2018-02-03
15710       15710  185090480  7123.500000  0.100000   True  2018-02-03
15711       15711  185090657  7128.172061  0.030500   True  2018-02-03
15712       15712  185090708  7134.433152  0.024440  False  2018-02-03
15713       15713  185090729  7136.199101  0.010000   True  2018-02-03
15714       15714  185090748  7136.200000  0.006030   True  2018-02-03

           time
0      02:00:08
1      02:00:09
2      02:00:09
3      02:00:10
4      02:00:26
5      02:00:26
6      02:00:38
7      02:00:38
8      02:00:38
9      02:00:39
10     02:01:15
11     02:01:55
12     02:01:55
13     02:01:55
14     02:01:55
15     02:01:55
16     02:01:55
17     02:02:00
18     02:02:07
19     02:02:07
20     02:02:07
21     02:02:07
22     02:02:07
23     02:02:11
24     02:02:19
25     02:02:21
26     02:02:36
27     02:04:31
28     02:05:02
29     02:05:15
...         ...
15685  01:54:35
15686  01:54:35
15687  01:54:35
15688  01:54:36
15689  01:55:06
15690  01:56:04
15691  01:56:23
15692  01:56:23
15693  01:56:23
15694  01:56:23
15695  01:56:23
15696  01:56:53
15697  01:56:54
15698  01:57:00
15699  01:57:09
15700  01:58:05
15701  01:58:05
15702  01:58:07
15703  01:58:10
15704  01:58:11
15705  01:58:11
15706  01:58:44
15707  01:58:45
15708  01:58:53
15709  01:58:53
15710  01:58:58
15711  01:59:17
15712  01:59:22
15713  01:59:33
15714  01:59:33

[15715 rows x 7 columns]

In [20]:
def count_avg(file):
    new = file[['price','amount']]
    return pd.Series({'unit_price': (new['price']/new['amount']),'total_price':(new['price']*new['amount'])})

In [21]:
#print (count_avg(data))

data.apply(count_avg, axis = 1)

         unit_price   total_price
0      1.608932e+06     33.572973
1      7.354680e+05     73.546804
2      1.610044e+06     33.596180
3      7.182600e+04    753.071840
4      8.481644e+04    635.792221
5      3.583744e+04   1504.892982
6      2.452000e+04   2206.800000
7      8.360542e+04    647.550016
8      7.355800e+04    735.580000
9      8.343802e+04    646.253460
10     3.676141e+06     14.704564
11     2.450440e+04   2205.396060
12     2.450440e+04   2205.396060
13     2.449441e+04   2204.496510
14     2.446442e+04   2201.797861
15     2.448108e+04   2203.297111
16     7.339826e+04    733.982595
17     1.502232e+06     35.852506
18     1.048419e+05    513.725408
19     3.623461e+04   1487.005891
20     1.834913e+04   2935.861436
21     3.447636e+05    156.222869
22     1.223276e+04   4403.792154
23     1.227163e+04   4416.492079
24     4.268557e+04   1262.115916
25     1.747595e+04   3082.758000
26     3.039939e+04   1772.207627
27     7.334700e+03   7334.700000
28     1.235194e+04   4328.219326
29     7.300000e+05     73.000000
...             ...           ...
15685  3.575645e+05    143.025799
15686  1.821964e+04   2806.849794
15687  1.191868e+04   4290.725799
15688  9.111874e+03   5612.106016
15689  2.408896e+06     21.242907
15690  2.222102e+04   2299.350198
15691  1.472877e+06     34.615886
15692  1.516512e+06     33.619876
15693  6.678886e+04    763.374724
15694  8.193494e+04    622.261100
15695  1.539299e+05    331.221704
15696  4.947972e+04   1027.746041
15697  7.131100e+05     71.311000
15698  4.749333e+03  10686.000000
15699  4.602508e+04   1102.465442
15700  7.140500e+04    714.050000
15701  7.140831e+04    713.976876
15702  7.141000e+04    714.100000
15703  9.185016e+04    555.838827
15704  1.170245e+06     43.698727
15705  7.150900e+04    715.090000
15706  4.233307e+03  12049.248274
15707  7.598517e+03   6712.910211
15708  6.706406e+04    757.205846
15709  7.130400e+04    713.040000
15710  7.123500e+04    712.350000
15711  2.337106e+05    217.409248
15712  2.919163e+05    174.365546
15713  7.136199e+05     71.361991
15714  1.183449e+06     43.031286

[15715 rows x 2 columns]

In [22]:
import matplotlib.pyplot as plt
plt.style.use('classic')
%matplotlib inline

In [ ]:
plt.figure()
plt.plot(data['time'],data['price'])