In [38]:
import pandas as pd
bitdata = pd.read_csv('/Users/yuqizhang/my-python-project/cryptoBabes/Bitfinex_BTCEUR_trades_2018_02_02.csv')
print(bitdata)

              id exchange  symbol           date        price    amount   sell
0      183601815       bf  btceur  1517529608000  7349.600000  0.004568  False
1      183601825       bf  btceur  1517529609000  7354.680450  0.010000   True
2      183601823       bf  btceur  1517529609000  7354.680450  0.004568   True
3      183601833       bf  btceur  1517529610000  7354.600000  0.102395  False
4      183601904       bf  btceur  1517529626000  7343.407500  0.086580  False
5      183601906       bf  btceur  1517529626000  7343.807250  0.204920  False
6      183602055       bf  btceur  1517529638000  7356.000000  0.300000  False
7      183602057       bf  btceur  1517529638000  7357.900000  0.088007  False
8      183602052       bf  btceur  1517529638000  7355.800000  0.100000  False
9      183602064       bf  btceur  1517529639000  7343.167650  0.088007  False
10     183602333       bf  btceur  1517529675000  7352.281950  0.002000   True
11     183602610       bf  btceur  1517529715000  7351.320200  0.300000   True
12     183602612       bf  btceur  1517529715000  7351.320200  0.300000   True
13     183602618       bf  btceur  1517529715000  7348.321701  0.300000   True
14     183602629       bf  btceur  1517529715000  7339.326204  0.300000   True
15     183602624       bf  btceur  1517529715000  7344.323702  0.300000   True
16     183602627       bf  btceur  1517529715000  7339.825954  0.100000   True
17     183602676       bf  btceur  1517529720000  7338.854490  0.004885   True
18     183602733       bf  btceur  1517529727000  7338.934400  0.070000  False
19     183602739       bf  btceur  1517529727000  7340.372780  0.202579  False
20     183602735       bf  btceur  1517529727000  7339.653590  0.400000  False
21     183602731       bf  btceur  1517529727000  7338.934400  0.021287  False
22     183602737       bf  btceur  1517529727000  7339.653590  0.600000  False
23     183602772       bf  btceur  1517529731000  7361.900000  0.599912  False
24     183602835       bf  btceur  1517529739000  7339.900000  0.171953   True
25     183602844       bf  btceur  1517529741000  7339.900000  0.420000   True
26     183602895       bf  btceur  1517529756000  7339.893320  0.241449  False
27     183603483       bf  btceur  1517529871000  7334.700000  1.000000   True
28     183604043       bf  btceur  1517529902000  7311.765000  0.591953   True
29     183604261       bf  btceur  1517529915000  7300.000000  0.010000   True
...          ...      ...     ...            ...          ...       ...    ...
15685  185088490       bf  btceur  1517615675000  7151.289936  0.020000   True
15686  185088492       bf  btceur  1517615675000  7151.209666  0.392500   True
15687  185088494       bf  btceur  1517615675000  7151.209666  0.600000   True
15688  185088507       bf  btceur  1517615676000  7151.000000  0.784800  False
15689  185088721       bf  btceur  1517615706000  7153.457237  0.002970   True
15690  185089418       bf  btceur  1517615764000  7148.000000  0.321677  False
15691  185089519       bf  btceur  1517615783000  7140.373162  0.004848  False
15692  185089521       bf  btceur  1517615783000  7140.373162  0.004708  False
15693  185089525       bf  btceur  1517615783000  7140.373162  0.106910  False
15694  185089517       bf  btceur  1517615783000  7140.373162  0.087147  False
15695  185089523       bf  btceur  1517615783000  7140.373162  0.046387  False
15696  185089729       bf  btceur  1517615813000  7131.100000  0.144122  False
15697  185089740       bf  btceur  1517615814000  7131.100000  0.010000  False
15698  185089799       bf  btceur  1517615820000  7124.000000  1.500000   True
15699  185089846       bf  btceur  1517615829000  7123.275566  0.154769  False
15700  185090070       bf  btceur  1517615885000  7140.500000  0.100000  False
15701  185090067       bf  btceur  1517615885000  7140.300000  0.099993  False
15702  185090085       bf  btceur  1517615887000  7141.000000  0.100000  False
15703  185090106       bf  btceur  1517615890000  7145.200000  0.077792  False
15704  185090112       bf  btceur  1517615891000  7151.100000  0.006111  False
15705  185090110       bf  btceur  1517615891000  7150.900000  0.100000  False
15706  185090357       bf  btceur  1517615924000  7142.000000  1.687097   True
15707  185090361       bf  btceur  1517615925000  7142.000000  0.939920   True
15708  185090429       bf  btceur  1517615933000  7126.100000  0.106258   True
15709  185090427       bf  btceur  1517615933000  7130.400000  0.100000   True
15710  185090480       bf  btceur  1517615938000  7123.500000  0.100000   True
15711  185090657       bf  btceur  1517615957000  7128.172061  0.030500   True
15712  185090708       bf  btceur  1517615962000  7134.433152  0.024440  False
15713  185090729       bf  btceur  1517615973000  7136.199101  0.010000   True
15714  185090748       bf  btceur  1517615973000  7136.200000  0.006030   True

[15715 rows x 7 columns]

In [39]:
import matplotlib.pyplot as plt
import dateandtime

In [40]:
def change_date(row):
    data = row['date']
    return pd.Series({'date':dateandtime.convert_dates(data)})

new_date = bitdata.apply(change_date, axis = 1)


print(new_date)

                     date
0     2018-02-02 02:00:08
1     2018-02-02 02:00:09
2     2018-02-02 02:00:09
3     2018-02-02 02:00:10
4     2018-02-02 02:00:26
5     2018-02-02 02:00:26
6     2018-02-02 02:00:38
7     2018-02-02 02:00:38
8     2018-02-02 02:00:38
9     2018-02-02 02:00:39
10    2018-02-02 02:01:15
11    2018-02-02 02:01:55
12    2018-02-02 02:01:55
13    2018-02-02 02:01:55
14    2018-02-02 02:01:55
15    2018-02-02 02:01:55
16    2018-02-02 02:01:55
17    2018-02-02 02:02:00
18    2018-02-02 02:02:07
19    2018-02-02 02:02:07
20    2018-02-02 02:02:07
21    2018-02-02 02:02:07
22    2018-02-02 02:02:07
23    2018-02-02 02:02:11
24    2018-02-02 02:02:19
25    2018-02-02 02:02:21
26    2018-02-02 02:02:36
27    2018-02-02 02:04:31
28    2018-02-02 02:05:02
29    2018-02-02 02:05:15
...                   ...
15685 2018-02-03 01:54:35
15686 2018-02-03 01:54:35
15687 2018-02-03 01:54:35
15688 2018-02-03 01:54:36
15689 2018-02-03 01:55:06
15690 2018-02-03 01:56:04
15691 2018-02-03 01:56:23
15692 2018-02-03 01:56:23
15693 2018-02-03 01:56:23
15694 2018-02-03 01:56:23
15695 2018-02-03 01:56:23
15696 2018-02-03 01:56:53
15697 2018-02-03 01:56:54
15698 2018-02-03 01:57:00
15699 2018-02-03 01:57:09
15700 2018-02-03 01:58:05
15701 2018-02-03 01:58:05
15702 2018-02-03 01:58:07
15703 2018-02-03 01:58:10
15704 2018-02-03 01:58:11
15705 2018-02-03 01:58:11
15706 2018-02-03 01:58:44
15707 2018-02-03 01:58:45
15708 2018-02-03 01:58:53
15709 2018-02-03 01:58:53
15710 2018-02-03 01:58:58
15711 2018-02-03 01:59:17
15712 2018-02-03 01:59:22
15713 2018-02-03 01:59:33
15714 2018-02-03 01:59:33

[15715 rows x 1 columns]

In [41]:
type(new_date)

pandas.core.frame.DataFrame

In [43]:
new_bitdata = bitdata.drop(columns=['exchange','symbol','date'])
new_bitdata.join(new_date)

              id        price    amount   sell                date
0      183601815  7349.600000  0.004568  False 2018-02-02 02:00:08
1      183601825  7354.680450  0.010000   True 2018-02-02 02:00:09
2      183601823  7354.680450  0.004568   True 2018-02-02 02:00:09
3      183601833  7354.600000  0.102395  False 2018-02-02 02:00:10
4      183601904  7343.407500  0.086580  False 2018-02-02 02:00:26
5      183601906  7343.807250  0.204920  False 2018-02-02 02:00:26
6      183602055  7356.000000  0.300000  False 2018-02-02 02:00:38
7      183602057  7357.900000  0.088007  False 2018-02-02 02:00:38
8      183602052  7355.800000  0.100000  False 2018-02-02 02:00:38
9      183602064  7343.167650  0.088007  False 2018-02-02 02:00:39
10     183602333  7352.281950  0.002000   True 2018-02-02 02:01:15
11     183602610  7351.320200  0.300000   True 2018-02-02 02:01:55
12     183602612  7351.320200  0.300000   True 2018-02-02 02:01:55
13     183602618  7348.321701  0.300000   True 2018-02-02 02:01:55
14     183602629  7339.326204  0.300000   True 2018-02-02 02:01:55
15     183602624  7344.323702  0.300000   True 2018-02-02 02:01:55
16     183602627  7339.825954  0.100000   True 2018-02-02 02:01:55
17     183602676  7338.854490  0.004885   True 2018-02-02 02:02:00
18     183602733  7338.934400  0.070000  False 2018-02-02 02:02:07
19     183602739  7340.372780  0.202579  False 2018-02-02 02:02:07
20     183602735  7339.653590  0.400000  False 2018-02-02 02:02:07
21     183602731  7338.934400  0.021287  False 2018-02-02 02:02:07
22     183602737  7339.653590  0.600000  False 2018-02-02 02:02:07
23     183602772  7361.900000  0.599912  False 2018-02-02 02:02:11
24     183602835  7339.900000  0.171953   True 2018-02-02 02:02:19
25     183602844  7339.900000  0.420000   True 2018-02-02 02:02:21
26     183602895  7339.893320  0.241449  False 2018-02-02 02:02:36
27     183603483  7334.700000  1.000000   True 2018-02-02 02:04:31
28     183604043  7311.765000  0.591953   True 2018-02-02 02:05:02
29     183604261  7300.000000  0.010000   True 2018-02-02 02:05:15
...          ...          ...       ...    ...                 ...
15685  185088490  7151.289936  0.020000   True 2018-02-03 01:54:35
15686  185088492  7151.209666  0.392500   True 2018-02-03 01:54:35
15687  185088494  7151.209666  0.600000   True 2018-02-03 01:54:35
15688  185088507  7151.000000  0.784800  False 2018-02-03 01:54:36
15689  185088721  7153.457237  0.002970   True 2018-02-03 01:55:06
15690  185089418  7148.000000  0.321677  False 2018-02-03 01:56:04
15691  185089519  7140.373162  0.004848  False 2018-02-03 01:56:23
15692  185089521  7140.373162  0.004708  False 2018-02-03 01:56:23
15693  185089525  7140.373162  0.106910  False 2018-02-03 01:56:23
15694  185089517  7140.373162  0.087147  False 2018-02-03 01:56:23
15695  185089523  7140.373162  0.046387  False 2018-02-03 01:56:23
15696  185089729  7131.100000  0.144122  False 2018-02-03 01:56:53
15697  185089740  7131.100000  0.010000  False 2018-02-03 01:56:54
15698  185089799  7124.000000  1.500000   True 2018-02-03 01:57:00
15699  185089846  7123.275566  0.154769  False 2018-02-03 01:57:09
15700  185090070  7140.500000  0.100000  False 2018-02-03 01:58:05
15701  185090067  7140.300000  0.099993  False 2018-02-03 01:58:05
15702  185090085  7141.000000  0.100000  False 2018-02-03 01:58:07
15703  185090106  7145.200000  0.077792  False 2018-02-03 01:58:10
15704  185090112  7151.100000  0.006111  False 2018-02-03 01:58:11
15705  185090110  7150.900000  0.100000  False 2018-02-03 01:58:11
15706  185090357  7142.000000  1.687097   True 2018-02-03 01:58:44
15707  185090361  7142.000000  0.939920   True 2018-02-03 01:58:45
15708  185090429  7126.100000  0.106258   True 2018-02-03 01:58:53
15709  185090427  7130.400000  0.100000   True 2018-02-03 01:58:53
15710  185090480  7123.500000  0.100000   True 2018-02-03 01:58:58
15711  185090657  7128.172061  0.030500   True 2018-02-03 01:59:17
15712  185090708  7134.433152  0.024440  False 2018-02-03 01:59:22
15713  185090729  7136.199101  0.010000   True 2018-02-03 01:59:33
15714  185090748  7136.200000  0.006030   True 2018-02-03 01:59:33

[15715 rows x 5 columns]

In [45]:
new_bitdata.to_csv('datawithnewdate.csv')